WIP Create CHANGELOG.md
teacher-army/community pull request #3
Opened 2022-09-01 20:03 UTC by kicumkicum

2022-09-21 22:21 UTC, zeckson requested changes
Я бы поправил навправление

2022-09-21 22:21 UTC, zeckson commented on CHANGELOG.md
> +08.08.2022 Добавили комментарии в Блоге
Ченджлог лучше вести от начала в конец, так проще добавлять изменения и читать обычно удобнее про то что было вначала, а не из конца в начало.
Как в книгах сверху-вниз слева-направо.

2022-09-22 08:19 UTC, kicumkicum commented on CHANGELOG.md
> +08.08.2022 Добавили комментарии в Блоге
На моей практике новые строки добавляют всегда вверх, чтобы сразу видеть последние изменения, а не самые первые. Примером может быть чейнджлог в ноде и реакте

2022-09-22 08:20 UTC, kicumkicum commented on CHANGELOG.md
> +01.08.2022 Провели Квартирник #1
```suggestion
01.09.2022 Провели Квартирник #1
```

2022-09-22 09:34 UTC, zeckson approved these changes

2022-09-22 09:34 UTC, zeckson commented on CHANGELOG.md
> +08.08.2022 Добавили комментарии в Блоге
Согласен

2022-09-23 08:55 UTC, Rapieree commented on CHANGELOG.md
> +30.06.2021 Задеплоили простенькую страничку
Если о странице на нексте и при мне, я примерно с 18.11.2021 работать начал

2022-09-23 09:02 UTC, Rapieree approved these changes

2022-09-23 09:02 UTC, Rapieree commented on CHANGELOG.md
> +30.06.2021 Задеплоили простенькую страничку
Вопросов нет

2022-09-23 09:17 UTC, merged